MOCK_CUSTOMERS = {
    "usr_99": {"name": "John Doe", "past_refunds": 1},
    "usr_100": {"name": "Jane Smith", "past_refunds": 2},
    "usr_101": {"name": "Alice Johnson", "past_refunds": 1},
    "usr_102": {"name": "Bob Brown", "past_refunds": 0},
    "usr_103": {"name": "Charlie Davis", "past_refunds": 3},
    "usr_104": {"name": "Diana Evans", "past_refunds": 0},
    "usr_105": {"name": "Evan Wright", "past_refunds": 1},
    "usr_106": {"name": "Fiona Green", "past_refunds": 5},
}

MOCK_ORDERS = {
    "ORD1234": {
        "customer_id": "usr_99",
        "item": "Wireless Headphones",
        "status": "Shipped - Arriving Tomorrow",
        "amount": 89.99,
        "days_since_purchase": 10,
        "refunded": True,
    },
    "ORD9941": {
        "customer_id": "usr_100",
        "item": "Office Chair",
        "status": "Delivered",
        "amount": 650.00,
        "days_since_purchase": 40,
        "refunded": False,
    },
    "ORD5678": {
        "customer_id": "usr_99",
        "item": "Gaming Mouse",
        "status": "Delivered",
        "amount": 49.99,
        "days_since_purchase": 5,
        "refunded": False,
    },
    "ORD1111": {
        "customer_id": "usr_101",
        "item": "Laptop Stand",
        "status": "Processing",
        "amount": 25.50,
        "days_since_purchase": 1,
        "refunded": False,
    },
    "ORD2222": {
        "customer_id": "usr_102",
        "item": "Mechanical Keyboard",
        "status": "Shipped - In Transit",
        "amount": 120.00,
        "days_since_purchase": 3,
        "refunded": False,
    },
    "ORD3333": {
        "customer_id": "usr_103",
        "item": "USB-C Hub",
        "status": "Delivered",
        "amount": 35.99,
        "days_since_purchase": 15,
        "refunded": False,
    },
    "ORD4444": {
        "customer_id": "usr_104",
        "item": "Monitor 27 inch",
        "status": "Delivered",
        "amount": 299.99,
        "days_since_purchase": 45,
        "refunded": False,
    },
    "ORD5555": {
        "customer_id": "usr_105",
        "item": "Webcam 1080p",
        "status": "Delivered",
        "amount": 59.99,
        "days_since_purchase": 25,
        "refunded": True,
    },
    "ORD6666": {
        "customer_id": "usr_106",
        "item": "Ergonomic Footrest",
        "status": "Cancelled",
        "amount": 29.99,
        "days_since_purchase": 50,
        "refunded": True,
    },
    "ORD7777": {
        "customer_id": "usr_99",
        "item": "Desk Mat",
        "status": "Delivered",
        "amount": 19.99,
        "days_since_purchase": 8,
        "refunded": False,
    },
    "ORD8888": {
        "customer_id": "usr_100",
        "item": "Bluetooth Speaker",
        "status": "Shipped - Arriving Today",
        "amount": 45.00,
        "days_since_purchase": 2,
        "refunded": False,
    },
    "ORD9090": {
        "customer_id": "usr_101",
        "item": "External Hard Drive 2TB",
        "status": "Delivered",
        "amount": 85.00,
        "days_since_purchase": 12,
        "refunded": False,
    },
    "ORD1212": {
        "customer_id": "usr_102",
        "item": "Noise Cancelling Earbuds",
        "status": "Processing",
        "amount": 150.00,
        "days_since_purchase": 0,
        "refunded": False,
    },
    "ORD3434": {
        "customer_id": "usr_103",
        "item": "Smart Desk Lamp",
        "status": "Delivered",
        "amount": 65.99,
        "days_since_purchase": 60,
        "refunded": False,
    },
    "ORD5656": {
        "customer_id": "usr_104",
        "item": "Standing Desk",
        "status": "Shipped - In Transit",
        "amount": 450.00,
        "days_since_purchase": 4,
        "refunded": False,
    }
}
